apiVersion: v1
kind: Service
metadata:
  name: wordpress-nodeport-svc
  namespace: wordpress-env
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30008