apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress-app
type: Opaque
data:
  mysql-root-password: bXlzcWxyb290cGFzc3dvcmQ=  # Base64 encoded password
  mysql-password: bXlzcWxwYXNzd29yZA==              # Base64 encoded password

---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress-app
type: Opaque
data:
  wordpress-db-password: bXlzcWxwYXNzd29yZA==        # Base64 encoded password